# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NavSatStatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NavSatStatus.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12NavSatStatus.proto\"/\n\x0cNavSatStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07service\x18\x02 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NAVSATSTATUS = _descriptor.Descriptor(
  name='NavSatStatus',
  full_name='NavSatStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='NavSatStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service', full_name='NavSatStatus.service', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['NavSatStatus'] = _NAVSATSTATUS

NavSatStatus = _reflection.GeneratedProtocolMessageType('NavSatStatus', (_message.Message,), dict(
  DESCRIPTOR = _NAVSATSTATUS,
  __module__ = 'NavSatStatus_pb2'
  # @@protoc_insertion_point(class_scope:NavSatStatus)
  ))
_sym_db.RegisterMessage(NavSatStatus)


# @@protoc_insertion_point(module_scope)
