# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Odometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Header_pb2 as Header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Odometry.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0eOdometry.proto\x1a\x0cHeader.proto\"#\n\x08Odometry\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Headerb\x06proto3')
  ,
  dependencies=[Header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ODOMETRY = _descriptor.Descriptor(
  name='Odometry',
  full_name='Odometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='Odometry.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=67,
)

_ODOMETRY.fields_by_name['header'].message_type = Header__pb2._HEADER
DESCRIPTOR.message_types_by_name['Odometry'] = _ODOMETRY

Odometry = _reflection.GeneratedProtocolMessageType('Odometry', (_message.Message,), dict(
  DESCRIPTOR = _ODOMETRY,
  __module__ = 'Odometry_pb2'
  # @@protoc_insertion_point(class_scope:Odometry)
  ))
_sym_db.RegisterMessage(Odometry)


# @@protoc_insertion_point(module_scope)
