# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PointCloud2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Header_pb2 as Header__pb2
import PointXYZRGB_pb2 as PointXYZRGB__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PointCloud2.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11PointCloud2.proto\x1a\x0cHeader.proto\x1a\x11PointXYZRGB.proto\"D\n\x0bPointCloud2\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x1c\n\x06points\x18\x02 \x03(\x0b\x32\x0c.PointXYZRGBb\x06proto3')
  ,
  dependencies=[Header__pb2.DESCRIPTOR,PointXYZRGB__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POINTCLOUD2 = _descriptor.Descriptor(
  name='PointCloud2',
  full_name='PointCloud2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='PointCloud2.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points', full_name='PointCloud2.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=122,
)

_POINTCLOUD2.fields_by_name['header'].message_type = Header__pb2._HEADER
_POINTCLOUD2.fields_by_name['points'].message_type = PointXYZRGB__pb2._POINTXYZRGB
DESCRIPTOR.message_types_by_name['PointCloud2'] = _POINTCLOUD2

PointCloud2 = _reflection.GeneratedProtocolMessageType('PointCloud2', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUD2,
  __module__ = 'PointCloud2_pb2'
  # @@protoc_insertion_point(class_scope:PointCloud2)
  ))
_sym_db.RegisterMessage(PointCloud2)


# @@protoc_insertion_point(module_scope)
