# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PoseWithCovariance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Pose_pb2 as Pose__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PoseWithCovariance.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18PoseWithCovariance.proto\x1a\nPose.proto\")\n\x12PoseWithCovariance\x12\x13\n\x04pose\x18\x01 \x01(\x0b\x32\x05.Poseb\x06proto3')
  ,
  dependencies=[Pose__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POSEWITHCOVARIANCE = _descriptor.Descriptor(
  name='PoseWithCovariance',
  full_name='PoseWithCovariance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='PoseWithCovariance.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=81,
)

_POSEWITHCOVARIANCE.fields_by_name['pose'].message_type = Pose__pb2._POSE
DESCRIPTOR.message_types_by_name['PoseWithCovariance'] = _POSEWITHCOVARIANCE

PoseWithCovariance = _reflection.GeneratedProtocolMessageType('PoseWithCovariance', (_message.Message,), dict(
  DESCRIPTOR = _POSEWITHCOVARIANCE,
  __module__ = 'PoseWithCovariance_pb2'
  # @@protoc_insertion_point(class_scope:PoseWithCovariance)
  ))
_sym_db.RegisterMessage(PoseWithCovariance)


# @@protoc_insertion_point(module_scope)
