# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SEVData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PointCloud2_pb2 as PointCloud2__pb2
import Image_pb2 as Image__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SEVData.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rSEVData.proto\x1a\x11PointCloud2.proto\x1a\x0bImage.proto\"%\n\x07SEVData\x12\x1a\n\nleft_image\x18\x01 \x01(\x0b\x32\x06.Imageb\x06proto3')
  ,
  dependencies=[PointCloud2__pb2.DESCRIPTOR,Image__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SEVDATA = _descriptor.Descriptor(
  name='SEVData',
  full_name='SEVData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_image', full_name='SEVData.left_image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=86,
)

_SEVDATA.fields_by_name['left_image'].message_type = Image__pb2._IMAGE
DESCRIPTOR.message_types_by_name['SEVData'] = _SEVDATA

SEVData = _reflection.GeneratedProtocolMessageType('SEVData', (_message.Message,), dict(
  DESCRIPTOR = _SEVDATA,
  __module__ = 'SEVData_pb2'
  # @@protoc_insertion_point(class_scope:SEVData)
  ))
_sym_db.RegisterMessage(SEVData)


# @@protoc_insertion_point(module_scope)
