# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Twist.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector3_pb2 as Vector3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Twist.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bTwist.proto\x1a\rVector3.proto\"<\n\x05Twist\x12\x18\n\x06linear\x18\x01 \x01(\x0b\x32\x08.Vector3\x12\x19\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x08.Vector3b\x06proto3')
  ,
  dependencies=[Vector3__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TWIST = _descriptor.Descriptor(
  name='Twist',
  full_name='Twist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear', full_name='Twist.linear', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular', full_name='Twist.angular', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=90,
)

_TWIST.fields_by_name['linear'].message_type = Vector3__pb2._VECTOR3
_TWIST.fields_by_name['angular'].message_type = Vector3__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['Twist'] = _TWIST

Twist = _reflection.GeneratedProtocolMessageType('Twist', (_message.Message,), dict(
  DESCRIPTOR = _TWIST,
  __module__ = 'Twist_pb2'
  # @@protoc_insertion_point(class_scope:Twist)
  ))
_sym_db.RegisterMessage(Twist)


# @@protoc_insertion_point(module_scope)
