# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TwistWithCovariance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Twist_pb2 as Twist__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TwistWithCovariance.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x19TwistWithCovariance.proto\x1a\x0bTwist.proto\",\n\x13TwistWithCovariance\x12\x15\n\x05twist\x18\x01 \x01(\x0b\x32\x06.Twistb\x06proto3')
  ,
  dependencies=[Twist__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TWISTWITHCOVARIANCE = _descriptor.Descriptor(
  name='TwistWithCovariance',
  full_name='TwistWithCovariance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='twist', full_name='TwistWithCovariance.twist', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=86,
)

_TWISTWITHCOVARIANCE.fields_by_name['twist'].message_type = Twist__pb2._TWIST
DESCRIPTOR.message_types_by_name['TwistWithCovariance'] = _TWISTWITHCOVARIANCE

TwistWithCovariance = _reflection.GeneratedProtocolMessageType('TwistWithCovariance', (_message.Message,), dict(
  DESCRIPTOR = _TWISTWITHCOVARIANCE,
  __module__ = 'TwistWithCovariance_pb2'
  # @@protoc_insertion_point(class_scope:TwistWithCovariance)
  ))
_sym_db.RegisterMessage(TwistWithCovariance)


# @@protoc_insertion_point(module_scope)
