# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgs/PointCloud2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msgs/PointCloud2.proto',
  package='tutorial',
  serialized_pb=_b('\n\x16msgs/PointCloud2.proto\x12\x08tutorial\"\x1a\n\x06Header\x12\x10\n\x08\x66rame_id\x18\x01 \x02(\t\"N\n\x0bPointCloud2\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.tutorial.Header\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12\r\n\x05width\x18\x03 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='tutorial.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='tutorial.Header.frame_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=62,
)


_POINTCLOUD2 = _descriptor.Descriptor(
  name='PointCloud2',
  full_name='tutorial.PointCloud2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tutorial.PointCloud2.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='tutorial.PointCloud2.height', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='tutorial.PointCloud2.width', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=142,
)

_POINTCLOUD2.fields_by_name['header'].message_type = _HEADER
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['PointCloud2'] = _POINTCLOUD2

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'msgs.PointCloud2_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Header)
  ))
_sym_db.RegisterMessage(Header)

PointCloud2 = _reflection.GeneratedProtocolMessageType('PointCloud2', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUD2,
  __module__ = 'msgs.PointCloud2_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.PointCloud2)
  ))
_sym_db.RegisterMessage(PointCloud2)


# @@protoc_insertion_point(module_scope)
